# Generated by Django 3.2.9 on 2021-12-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211209_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(related_name='tag', through='articles.ArticleScopes', to='articles.Article'),
        ),
    ]
